language: php

os: linux

services:
  - mysql

php:
  - 7.2
  - 7.3
  - 7.4

addons:
    code_climate:
        repo_token: a4a2b434edd8850ccf5354c3dc1202b1c824cd442fe7c4c5a2d0d82edef1cae0

env:
    - APP_ENV=testing DB_CONNECTION=mysql DB_DATABASE=travis_db DB_USERNAME=travis DB_PASSWORD= CACHE_DRIVER=array SESSION_DRIVER=array QUEUE_DRIVER=sync

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - COMPOSER_DISCARD_CHANGES=1 composer install --prefer-source --no-interaction

before_script:
  - mysql -e 'create database travis_db;'

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter
